SELECT DISTINCT a.CAR_ID AS car_id,
    CASE
        WHEN AVAILABILITY IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN
    (SELECT
        CAR_ID,
        '대여중' AS AVAILABILITY
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        DATE('2022-10-16') BETWEEN START_DATE AND END_DATE
    ) b 
ON a.CAR_ID = b.CAR_ID
ORDER BY 
    CAR_ID DESC;